import type { Metadata } from 'next';
import { Inter, Space_Grotesk } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-spaceGrotesk',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable}`}
        suppressHydrationWarning={true}
      >
        {/* <Container> */}

        <Theme
          appearance="light"
          accentColor="orange"
          grayColor="sand"
          scaling="110%"
        >
          {/* <Theme appearance="light" accentColor="indigo" scaling="110%"> */}
          {/* <Theme accentColor="green"> */}
          <ClerkProvider>{children}</ClerkProvider>
          {/* <ThemePanel /> */}
        </Theme>

        {/* </Container> */}
      </body>
    </html>
  );
}
